### ISSUE TITLE
Add more info for configuring pulseaudio (cgmanager, elogind, etc)

### ISSUE THREAD

**Issue by sburris0** [void-linux/void-docs#312]
More details about installing pulseaudio from someone with better understanding of the matter would be greatly appreciated. The old wiki referenced `cgmanager` and `ConsoleKit2`, the latter of which I understand was replaced by `elogind`? I just did a clean install and wasn't sure about the use of `cgmanager`. 

Information needed:
1. Services pulseaudio depends on (`cgmanager`(?), `alsa-utils`, ...)
2. Relevant symlinks (`# ln -s /etc/sv/cgmanager /var/service`)

Additionally, an explanation somewhere (or link if it exists) about the removal of `ConsoleKit2` and the use of `polkit` would be very helpful.

**Comment by ericonr** [comment]
So, in parts:

- `cgmanager` was a dependency of `ConsoleKit2`, and has been removed from voi-packages as well. `elogind` is a replacement for both, at least in the important parts.
- Pulse is documented, I think we are only lacking the `alsa` service. (should be fixed)
- We avoid having commands repeated throughout the documentation, so we document that the service needs to be enabled and one can check the services section for how to do so.
- What do you think needs to be said about ConsoleKit2? It has been removed and isn't relevant to Void anymore, so I don't see much of a need for it. I am open to being corrected in this, though.
- I am very far from versed in the use of `polkit`, and I believe most of its usage is distro agnostic, so documenting it here is probably not the correct place - unless external/upstream resources suck, and even then it's preferable to make those resources better. What do you think is lacking in regards to polkit? I believe there's some effort in providing reasonable rules in void-packages.

**Comment by sburris0** [comment]
Is `cgmanager` currently pending deletion? I still see it.
I think just noting that `elogind` mostly replaces `cgmanager` and `ConsoleKit2` would be quite helpful, as the change came as a surprise to me when doing a new install.
That, and mentioning `alsa-utils` as a dependency would be sufficient.

I thought `polkit` and `ConsoleKit2` were related somehow for some reason, it isn't relevant here.

Thanks for the quick response.

**Comment by ericonr** [comment]
It is pending deletion, yes.

> I think just noting that elogind mostly replaces cgmanager and ConsoleKit2

That's fair, I think. Since the main component there was ConsoleKit2, would you be ok with only it being mentioned? Since `cgmanager` was mostly a "helper" for CK2, from what I understand.

Glad to help c:

**Comment by sburris0** [comment]
I don't know much about the two, so my judgement isn't very good here, but I think `cgmanager` is worth a short mention because it's still a change from the previous setup and what is stated on the deprecated wiki page.

**Comment by flexibeast** [comment]
i'm not sure there's any need for further information (though there does need to be a correction):

* Pulse doesn't depend on the `alsa` service, nor on `elogind` (i don't use either). However, `elogind` is already mentioned:

> There are several methods of allowing PulseAudio to access to audio devices. The simplest one is to add your user to the audio group. Alternatively, you can use a session manager, like elogind.

* Pulse doesn't require the installation of `alsa-utils`, as far as i'm aware.

* The `alsa` service merely restores previous ALSA settings:

```
alsactl restore
exec chpst -b alsa pause
```
* The `alsa` service is mentioned in [the ALSA section](https://docs.voidlinux.org/config/media/alsa.html).

* i don't know of any specific configuration that needs to be done with `polkit`; i've certainly not needed to do any. There might be particular issues resulting from the use of certain DEs, but if so, that needs to either be addressed in the packaging for those DEs, or in Handbook sections for those DEs.

* i don't know if `cgmanager` was actually needed in the past - the wiki had lots of incorrect/unvetted information, which is one of the reasons Void decided to move away from it. However, even if it did, i think the Handbook should generally only describe the *current* requirements for using Void, not past requirements, which would end up adding a lot of clutter.

* The page does need a correction: it is not true that a D-BUS system bus is required. A session bus *might* be required (i use one), but i'm not sure of that; i think one can simply start `pulseaudio` manually.

**Comment by flexibeast** [comment]
The last point in my previous comment has now been addressed by https://github.com/void-linux/void-docs/commit/be10ec115250cf2502ed0eb1d8f793e43a1f0fdd, so i'm closing this.
